application: carepackage-cssi
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /myfavicon\.ico
  static_files: myfavicon.ico
  upload: myfavicon\.ico

- url: /images
  static_dir: images

- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /
  script: main.app
  login: optional

- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
